[package]
name = "rust_l402"
version = "0.1.0"
edition = "2021"

[dependencies]
lnd-grpc-tonic-client = "0.3.0"
reqwest = "0.12.5"
tonic_lnd = "0.5.1"

[crate.workspace]
members = [
    "client",
    "lnd-grpc-tonic-client",
    "tonic_lnd",
]
