[package]
name = "rust_l402"
authors = ["AreaLayer"]
description = "Rust L402 Client"
license = "MIT"
repository = "https://github.com/AreaLayer/rust-l402"
homepage = "https://www.arealayer.net/projects"
version = "2.0.0-beta.2"
edition = "2021"

[dependencies]
lnd-grpc-tonic-client = "0.3.0"
reqwest = "0.12.7"
tonic_lnd = "0.5.1"
webpki = "0.22.4"
sha2 = "0.10.8"
nostr = "0.35.0"
tonic = "=0.12.2"

[package.metadata]
tags = ["rust", "lnd", "grpc", "tonic", "client", "bitcoin", "lightning"]

[crate.workspace]
members = [
    "client",
    "lnd-grpc-tonic-client",
    "tonic_lnd",
    "wallet",
    "lib",
    "tokenstore",
    "example",
    "nostr",
    "proxy",
]
