[package]
name = "rust_l402"
authors = ["AreaLayer"]
description = "Rust L402 Client"
license = "MIT"
repository = "https://github.com/AreaLayer/rust-l402"
homepage = "https://www.arealayer.net/products"
tags = ["rust", "lnd", "grpc", "tonic", "client", "bitcoin", "lightning"]
version = "0.1.0-beta"
edition = "2021"

[dependencies]
lnd-grpc-tonic-client = "0.3.0"
reqwest = "0.12.5"
tonic_lnd = "0.5.1"

[crate.workspace]
members = [
    "client",
    "lnd-grpc-tonic-client",
    "tonic_lnd",
    "wallet",
    "lib",
    "tokenstore",
]
